as.df.for.box.plot <- function( p.mut.mtrxs.list, distance.column.index,
  p.column.index, lapply.funk=lapply ) {
  # Prepares mutation probability matrices in argument list 'p.mut.mtrxs.list'
  # for a boxplot with ggplot2.
  #
  # Example plot:
  #--------------
  # ggplot( as.df.for.box.plot( p.mut.mtrxs.list, 3, 1, mclapply ), aes(
  # factor( p.mutation.Sequence.Distance.grid ), min.Sequence.Distance ) ) +
  # geom_boxplot()
  #
  # Args:
  #  p.mut.mtrxs.list      : The list of mutation probability matrices as
  #                          result of multiple function calls of function
  #                          'gridPMutation'
  #  distance.column.index : The integer index of the column to be box plotted,
  #                          i.e. 'min.Sequence.Distance'.
  #  p.column.index        : The integer index of the column holding the
  #                          gridded mutation probabilities, i.e.
  #                          'p.mutation.Sequence.Distance.grid'.
  #  lapply.funk           : Set to 'mclapply' if parallel execution is wanted.
  #
  # Returns: A data.frame that can be fed into a ggplot call. See example above.
  #   
  as.data.frame( 
    do.call( 'rbind', 
      lapply.funk( p.mut.mtrxs.list, function( mtrx ) {
        mtrx[ , c( p.column.index, distance.column.index ), drop=F ]
      })
    )
  )
}

goAnnotationAbbreviations <- function( protein.accessions, anno.mtrx, go.type.annos,
  go.type.anno.space, unknown.anno.abbrev='ø', go.type.abbrevs=list(
    'biological_process'='B', 'cellular_component'='C',
    'molecular_function'='M' ) ) {
  # Generates abbreviations for Gene Ontology term annotations, so that i.e. in
  # the plotted phylogenetic tree each protein accession can be suffixed with a
  # six character text in which each two characters consist of the abbreviated
  # GO type followed by the annotated indexed unique GO terms. I.e.: 'B2CøM2'.
  #
  # Args:
  #  protein.accessions  : accessions of the proteins whose annotations shall
  #                        be abbreviated.
  #  anno.mtrx           : The annotation matrix as i.e. returned by
  #                        retrieveUniprotAnnotations(…)
  #  go.type.annos       : The result of calling goTypeAnnotationMatrices(
  #                        anno.mtrx, … )
  #  go.type.anno.space  : The result of calling goAnnotationSpaceList(
  #                        go.type.annos, … )
  #  unknown.anno.abbrev : The string to be used to abbreviate the annotation
  #                        'unknown'. Default: 'ø'
  #  go.type.abbrevs     : The abbreviations usd for each GO type, i.e. 'B' for
  #                        'biological_process'
  #
  # Returns: A named list which contains a list of abbreviated GO annotations
  # for each protein accession in anno.mtrx.
  #   
  setNames(
    lapply( protein.accessions, function( acc ) {
      setNames(
        lapply( names( go.type.anno.space ), function( go.type ) {
          paste( go.type.abbrevs[[ go.type ]],
            if ( acc %in% colnames( go.type.annos[[ go.type ]] ) ) {
              anno <- go.type.annos[[ go.type ]][[ 'GO', acc ]]
              which( as.logical(
                lapply( go.type.anno.space[[ go.type ]], identical, anno )
              ) )
            } else {
              unknown.anno.abbrev
            },
            sep=''
          )
        }),
        names( go.type.anno.space )
      )
    }),
    colnames( anno.mtrx )
  )
}

goAnnotationSpaceAbbreviations <- function( go.anno.spaces,
  abbrev.colnames=c( 'Abbreviation', 'Annotated GO terms' ),
  go.type.abbrevs=list( 'biological_process'='B', 'cellular_component'='C',
    'molecular_function'='M' )
  ) {
  # Generates a table for each Gene Ontology term type mapping the unique
  # annotations to an index. This is meant to be the caption for a PhyloFun
  # plotted phylogenetic tree using abbreviated GO term annotations obtained by
  # calling goAnnotationAbbreviations(…).
  #
  # Args:
  #  go.anno.spaces  : A list of uniquely annotated GO terms for each GO term
  #                    type. Generated by function goAnnotationSpaceList(…).
  #  abbrev.colnames : The column names for each of the abbreviation tables.
  #  go.type.abbrevs : The abbreviations used for each GO term type.
  #
  # Returns: A list of abbreviation tables, one for each GO term type.
  #   
  setNames(
    lapply( names( go.anno.spaces ), function( go.type ) {
      gt.anno.space <- go.anno.spaces[[ go.type ]]
      max.ind <- length( gt.anno.space )
      abbrevs <- paste( go.type.abbrevs[[ go.type ]],
        as.character( 1:max.ind ), sep=''
      )
      gt.annos <- as.character(
        lapply( go.anno.spaces[[ go.type ]], toString )
      )
      matrix( c( abbrevs, gt.annos ),
        nrow=max.ind, dimnames=list( c(), abbrev.colnames )
      )
    }),
    names( go.anno.spaces )
  )
}
